apiVersion: "k0sctl.k0sproject.io/v1beta1"
kind: "cluster"
spec:
  hosts:
  - installFlags:
    - "--enable-cloud-provider"
    - "--kubelet-extra-args=\"--cloud-provider=external\""
    role: "controller+worker"
    ssh:
      address: "3.71.26.221"
      keyPath: "./aws_private.pem"
      user: "ubuntu"
  k0s:
    config:
      apiVersion: "k0s.k0sproject.io/v1beta1"
      kind: "Cluster"
      metadata:
        name: "k0smotron-cluster"
      spec:
        api:
          address: "3.71.26.221"
          externalAddress: "3.71.26.221"
          k0sApiPort: 9443
          port: 6443
          sans:
          - "3.71.26.221"
          tunneledNetworkingMode: false
        controllerManager: {}
        extensions:
          helm:
            charts:
            - chartname: "aws-cloud-controller-manager/aws-cloud-controller-manager"
              name: "a-aws-cloud-controller-manager"
              namespace: "kube-system"
              values: |
                args:
                  - --v=2
                  - --cloud-provider=aws
                  - --allocate-node-cidrs=false
                  - --cluster-cidr=172.20.0.0/16
                  - --cluster-name="k0smotron-cluster"
                image:
                  repository: registry.k8s.io/provider-aws/cloud-controller-manager
                  tag: v1.27.1
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
              version: "0.0.7"
            - chartname: "aws-ebs-csi-driver/aws-ebs-csi-driver"
              name: "b-aws-ebs-csi-driver"
              namespace: "kube-system"
              values: |
                node:
                  kubeletPath: /var/lib/k0s/kubelet
              version: "2.17.2"
            repositories:
            - name: "aws-cloud-controller-manager"
              url: "https://kubernetes.github.io/cloud-provider-aws"
            - name: "aws-ebs-csi-driver"
              url: "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
        installConfig:
          users:
            etcdUser: "etcd"
            kineUser: "kube-apiserver"
            konnectivityUser: "konnectivity-server"
            kubeAPIserverUser: "kube-apiserver"
            kubeSchedulerUser: "kube-scheduler"
        network:
          kubeProxy:
            disabled: false
            mode: "iptables"
          podCIDR: "10.244.0.0/16"
          serviceCIDR: "10.96.0.0/12"
        storage:
          type: "etcd"
        telemetry:
          enabled: true
    dynamicConfig: false
    version: "1.27.4+k0s.0"
